### Use CPU runtime

### Default model distilbert-base-uncased-finetuned-sst-2-english
* Goto https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english

In [1]:
from transformers import pipeline

help(pipeline)

Help on function pipeline in module transformers.pipelines:

pipeline(task: str = None, model: Union[str, ForwardRef('PreTrainedModel'), ForwardRef('TFPreTrainedModel'), NoneType] = None, config: Union[str, transformers.configuration_utils.PretrainedConfig, NoneType] = None, tokenizer: Union[str, transformers.tokenization_utils.PreTrainedTokenizer, ForwardRef('PreTrainedTokenizerFast'), NoneType] = None, feature_extractor: Union[str, ForwardRef('SequenceFeatureExtractor'), NoneType] = None, image_processor: Union[str, transformers.image_processing_utils.BaseImageProcessor, NoneType] = None, framework: Optional[str] = None, revision: Optional[str] = None, use_fast: bool = True, token: Union[str, bool, NoneType] = None, device: Union[int, str, ForwardRef('torch.device'), NoneType] = None, device_map=None, torch_dtype=None, trust_remote_code: Optional[bool] = None, model_kwargs: Dict[str, Any] = None, pipeline_class: Optional[Any] = None, **kwargs) -> transformers.pipelines.base.Pipeline


In [2]:
sa_pipeline = pipeline("sentiment-analysis")

sa_pipeline

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [3]:
sa_pipeline = pipeline("text-classification")

sa_pipeline

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [4]:
sa_pipeline("The weather was perfect for the outdoor event, and everyone had a fantastic time.")

[{'label': 'POSITIVE', 'score': 0.9998812675476074}]

In [5]:
sa_pipeline("I had a terrible experience with the customer service.")

[{'label': 'NEGATIVE', 'score': 0.9992349147796631}]

##### Observe this is a binary classifier ie only positive and negative

In [6]:
sa_pipeline("The movie was fantastic and I enjoyed every moment!")

[{'label': 'POSITIVE', 'score': 0.9998898506164551}]

In [8]:
sa_pipeline("The book was okay, nothing special.")

[{'label': 'NEGATIVE', 'score': 0.9899623394012451}]

In [9]:
sa_pipeline([
    "Missing the deadline was incredibly disappointing, especially after all the hard work we put in.",
    "The unexpected praise from my manager really boosted my confidence.",
    "The meeting lasted exactly one hour, as scheduled.",
    "Spending time with family always fills me with joy and gratitude."
])

[{'label': 'NEGATIVE', 'score': 0.9995641112327576},
 {'label': 'POSITIVE', 'score': 0.999849796295166},
 {'label': 'NEGATIVE', 'score': 0.8796570897102356},
 {'label': 'POSITIVE', 'score': 0.9998840093612671}]

In [10]:
print(sa_pipeline.model.config.id2label)

{0: 'NEGATIVE', 1: 'POSITIVE'}


Using the tokenizer and model separately

In [12]:
import tensorflow as tf

from transformers import DistilBertTokenizer, TFAutoModelForSequenceClassification

In [13]:
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

tokenizer

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

DistilBertTokenizer(name_or_path='distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [14]:
model = TFAutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

model

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [15]:
inputs = tokenizer("The constant delays are making it difficult for us to stay motivated on this project.", return_tensors="tf")

inputs

{'input_ids': <tf.Tensor: shape=(1, 18), dtype=int32, numpy=
array([[  101,  1996,  5377, 14350,  2024,  2437,  2009,  3697,  2005,
         2149,  2000,  2994, 12774,  2006,  2023,  2622,  1012,   102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 18), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int32)>}

In [16]:
logits = model(**inputs).logits

logits

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 4.47947  , -3.6256754]], dtype=float32)>

Using a negative value for the axis counts dimensions from the end of the shape, rather than the beginning. Specifically, axis=-1 refers to the last dimension of the tensor.

In [17]:
predicted_class_id = int(tf.math.argmax(logits, axis=-1)[0])

print(f"Predicted class id {predicted_class_id}")

print(f"Label {model.config.id2label[predicted_class_id]}")

Predicted class id 0
Label NEGATIVE


In [18]:
inputs = tokenizer("Winning the competition was one of the happiest moments of my life.", return_tensors="tf")

inputs

{'input_ids': <tf.Tensor: shape=(1, 17), dtype=int32, numpy=
array([[  101,  3045,  1996,  2971,  2001,  2028,  1997,  1996,  5292,
         9397, 10458,  5312,  1997,  2026,  2166,  1012,   102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 17), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [19]:
logits = model(**inputs).logits

logits

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-3.6673293,  4.001959 ]], dtype=float32)>

In [20]:
predicted_class_id = int(tf.math.argmax(logits, axis=-1)[0])

print(f"Predicted class id {predicted_class_id}")

print(f"Label {model.config.id2label[predicted_class_id]}")

Predicted class id 1
Label POSITIVE


* Goto "https://huggingface.co/"
* Click Models from the navbar
* Click "Text Classification" under NLP
* Click on cardiffnlp/twitter-roberta-base-sentiment-latest and check the page (This models is trained to understand emotions)

In [ ]:
sa_pipeline = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest")

sa_pipeline

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
print(sa_pipeline.model.config.id2label)

{0: 'negative', 1: 'neutral', 2: 'positive'}


In [ ]:
sa_pipeline("I finally completed the marathon, and the sense of accomplishment is overwhelming.")

[{'label': 'positive', 'score': 0.9842849373817444}]

In [ ]:
sa_pipeline("The meeting lasted exactly one hour, as scheduled.")

[{'label': 'neutral', 'score': 0.9426935911178589}]

In [ ]:
sa_pipeline("The book was okay, nothing special.")

[{'label': 'neutral', 'score': 0.579319179058075}]

In [ ]:
sa_pipeline("The movie was a complete waste of time.")

[{'label': 'negative', 'score': 0.9335517883300781}]

## Emotions


* Goto "https://huggingface.co/"
* Click Models from the navbar
* Click "Text Classification" under NLP
* Click on "j-hartmann/emotion-english-distilroberta-base" and check the page (This models is trained to understand emotions)

https://huggingface.co/j-hartmann/emotion-english-distilroberta-base

In [21]:
sa_pipeline = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")

sa_pipeline

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [22]:
print(sa_pipeline.model.config.id2label)

{0: 'anger', 1: 'disgust', 2: 'fear', 3: 'joy', 4: 'neutral', 5: 'sadness', 6: 'surprise'}


In [23]:
sa_pipeline("The dinner was absolutely delicious and well-prepared.")

[{'label': 'joy', 'score': 0.9052978754043579}]

In [24]:
sa_pipeline("I felt a deep sense of sorrow when I heard about the accident.")

[{'label': 'sadness', 'score': 0.9851123690605164}]

In [25]:
sa_pipeline("I was furious when I found out someone had lied to me.")

[{'label': 'anger', 'score': 0.9870098829269409}]

In [26]:
sa_pipeline([
    "The smell of the spoiled food made me feel nauseous.",
    "I was quite scared walking alone in the dark alley."
])

[{'label': 'disgust', 'score': 0.8893010020256042},
 {'label': 'fear', 'score': 0.994158148765564}]

## Financial sentiment

This models is trained specific to financial news: mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis

https://huggingface.co/mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis

In [27]:
sa_pipeline = pipeline("text-classification", model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")

sa_pipeline

config.json:   0%|          | 0.00/933 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [28]:
print(sa_pipeline.model.config.id2label)

{0: 'negative', 1: 'neutral', 2: 'positive'}


In [30]:
sa_pipeline("The economic news has lifted market spirits, pushing the index up by 2%.")

[{'label': 'positive', 'score': 0.9996492862701416}]

In [31]:
sa_pipeline([
    "The unexpected decline in consumer spending caused a negative reaction in the market, with stocks falling by 120 points.",
    "The company's strong quarterly earnings report fueled investor confidence.",
    "The company's stock remained unchanged despite the announcement of a new product launch."
])

[{'label': 'negative', 'score': 0.9988299012184143},
 {'label': 'positive', 'score': 0.9996589422225952},
 {'label': 'neutral', 'score': 0.999548614025116}]

##### We get neutral when we have statements that are not related to finance

In [32]:
sa_pipeline("The team completed the project successfully")

[{'label': 'neutral', 'score': 0.8386052846908569}]

In [33]:
sa_pipeline("The movie was a complete waste of time.")

[{'label': 'neutral', 'score': 0.7461015582084656}]

## Zero-shot Classification

- Go to https://huggingface.co/ -> Models
- Click on Zero-shot Classification on the left pane
- Search for facebook/bart-large-mnli
- Click on the model and show the details

In [34]:
zeroshot_pipeline = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

zeroshot_pipeline

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [36]:
text = "The fog crept silently through the darkened streets, swallowing the last remnants of daylight as the town braced for the unknown."

results = zeroshot_pipeline(text, candidate_labels=['romance', 'science fiction', 'horror', 'young adult', 'comedy'])

results

{'sequence': 'The fog crept silently through the darkened streets, swallowing the last remnants of daylight as the town braced for the unknown.',
 'labels': ['horror', 'science fiction', 'romance', 'young adult', 'comedy'],
 'scores': [0.6218446493148804,
  0.11909209191799164,
  0.10013627260923386,
  0.09492691606283188,
  0.06400011479854584]}

In [38]:
import pandas as pd

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

labels    scores
0           horror  0.621845
1  science fiction  0.119092
2          romance  0.100136
3      young adult  0.094927
4           comedy  0.064000

In [39]:
text = "The company's quarterly earnings report exceeded analysts' expectations, driving a significant uptick in stock prices."

results = zeroshot_pipeline(text, candidate_labels=['technology', 'politics', 'entertainment', 'climate change', 'business'])

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

labels    scores
0        business  0.931512
1      technology  0.037311
2   entertainment  0.014065
3  climate change  0.009554
4        politics  0.007558

Note that the probabilities do not sum up to 1

In [42]:
text = "The proposed legislation aims to address climate change by incentivizing green energy production, but it has sparked fierce debate among lawmakers over its economic impact."

results = zeroshot_pipeline(text, candidate_labels=['technology', 'climate change', 'politics', 'economics', 'finance', 'business', 'environment'], multi_label=True)

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

labels    scores
0  climate change  0.980663
1     environment  0.884044
2       economics  0.501290
3        politics  0.041952
4         finance  0.017039
5      technology  0.007905
6        business  0.002840

In [44]:
text = "As the ancient clock struck midnight, she uncovered the dusty tome that had been hidden away for centuries, its pages whispering secrets of a forgotten world."

results = zeroshot_pipeline(text, candidate_labels=['gothic', 'romance', 'politics', 'comedy', 'finance', 'mystery'], multi_label=True)

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

labels    scores
0   mystery  0.945307
1    gothic  0.315181
2   romance  0.238234
3   finance  0.028927
4  politics  0.009839
5    comedy  0.002895